=== teivah/TIBreview/src/main/resources/schemas/tibrules.xsd
<xs:schema xmlns="exchange.tibco.com/tibreview"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="exchange.tibco.com/tibreview" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tibrules" type="tibrules" />

	<xs:complexType name="tibrules">
		<xs:sequence>
			<xs:element name="process" type="process" minOccurs="0" />
			<xs:element name="resource" type="resource" minOccurs="0" />
			<xs:element name="xpathfunctions" type="xpathfunctions"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="process">
		<xs:sequence>
			<xs:element name="rule" type="rule" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="resource">
		<xs:sequence>
			<xs:element name="rule" type="resourcerule" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="xpathfunctions">
		<xs:sequence>
			<xs:element name="xpathfunction" type="xpathfunction"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="xpathfunction">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="rule">
		<xs:sequence>
			<xs:element name="impl" type="impl" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" />
		<xs:attribute type="xs:string" name="ruleset" />
		<xs:attribute type="xs:int" name="prority" />
		<xs:attribute type="xs:string" name="description" />
		<xs:attribute type="xs:boolean" name="global" use="optional" />
	</xs:complexType>

	<xs:complexType name="resourcerule">
		<xs:sequence>
			<xs:element name="configuration" type="configuration" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" />
		<xs:attribute type="xs:string" name="ruleset" />
		<xs:attribute type="xs:int" name="prority" />
		<xs:attribute type="xs:string" name="description" />
	</xs:complexType>

	<xs:complexType name="configuration">
		<xs:sequence>
			<xs:element name="property" type="property" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="type" />
	</xs:complexType>

	<xs:complexType name="property">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="check" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="impl">
		<xs:choice>
			<xs:element name="xpath" type="xpath" />
			<xs:element name="cond" type="cond" />
			<xs:element name="not" type="not" />
			<xs:element name="java" type="java" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="cond">
		<xs:sequence>
			<xs:element name="if" type="if" />
			<xs:element name="elseif" type="elseif" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="else" type="else" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="not">
		<xs:choice>
			<xs:element name="xpath" type="xpath" />
			<xs:element name="cond" type="cond" />
			<xs:element name="not" type="not" />
			<xs:element name="java" type="java" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="if">
		<xs:sequence>
			<xs:choice>
				<xs:element name="xpath" type="xpath" />
				<xs:element name="cond" type="cond" />
				<xs:element name="not" type="not" />
				<xs:element name="java" type="java" />
			</xs:choice>
			<xs:element name="then" type="impl" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="elseif">
		<xs:sequence>
			<xs:choice>
				<xs:element name="xpath" type="xpath" />
				<xs:element name="cond" type="cond" />
				<xs:element name="not" type="not" />
				<xs:element name="java" type="java" />
			</xs:choice>
			<xs:element name="then" type="impl" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="else">
		<xs:sequence>
			<xs:element name="then" type="impl" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="xpath">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string" use="optional" />
				<xs:attribute name="detail" type="xs:string" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="java">
		<xs:simpleContent>
			<xs:extension base="xs:string" />
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== teivah/TIBreview/src/test/resources/FileResources/xml/RendezvousResourceCertified.xml
<?xml version="1.0" encoding="UTF-8"?>
<tibrules xmlns="exchange.tibco.com/tibreview" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="exchange.tibco.com/tibreview ../../main/resources/schemas/tibrules.xsd ">
	<process>

	</process>


	
	
	<resource>
		<rule name="RV Transport Certified Configuration resource configuration error" ruleset="TIBCO conventions" prority="3"
			description="RV Transport Certified resource configuration error.">
			<configuration type="rvsharedresource:RVResource" filter=" @rvType = 'Certified' " >
				<property name="daemon" check="configurable"/>
				<property name="network" check="configurable"/>
				<property name="service" check="configurable"/>
				<property name="cmName" check="configurable"/>
				<property name="ledgerFile" check="configurable"/>
				<property name="syncLedgerFile" check="configurable"/>
				<property name="relayAgent" check="configurable"/>
				<property name="msgTimeout" check="configurable"/>
				<property name="requireOldMsg" check="configurable"/>

			</configuration>
		</rule>
	</resource>

	<xpathfunctions>
		<xpathfunction id="process">/bpws:process</xpathfunction>
		<xpathfunction id="scope">/bpws:process/bpws:scope</xpathfunction>
		<xpathfunction id="flow">/bpws:process/bpws:scope/bpws:flow</xpathfunction>
		<xpathfunction id="extensionActivity">//bpws:extensionActivity</xpathfunction>
		<xpathfunction id="extActivity">//tibex:extActivity</xpathfunction>
		<xpathfunction id="activityExtension">//tibex:activityExtension</xpathfunction>
		<xpathfunction id="activityExtensionConfig">//tibex:config</xpathfunction>
		<xpathfunction id="processInfo">/bpws:process/tibex:ProcessInfo</xpathfunction>
		<xpathfunction id="receiveEvent">//bpws:extensionActivity/tibex:receiveEvent</xpathfunction>
		<xpathfunction id="eventSource">//bpws:extensionActivity/tibex:receiveEvent/tibex:eventSource</xpathfunction>
		<xpathfunction id="documentation">/bpws:process/bpws:documentation</xpathfunction>
		<xpathfunction id="reply">//bpws:reply</xpathfunction>
		<xpathfunction id="layoutConstraint">//layoutConstraint</xpathfunction>
		<xpathfunction id="diagram">//notation:Diagram</xpathfunction>
	</xpathfunctions>
</tibrules>

=== teivah/TIBreview/src/test/resources/FileResources/xml/FTLRealmServerConnection.xml
<?xml version="1.0" encoding="UTF-8"?>
<tibrules xmlns="exchange.tibco.com/tibreview" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="exchange.tibco.com/tibreview ../../main/resources/schemas/tibrules.xsd ">
	<process>

	</process>


	<resource>
		<rule name="FTL Realm Fresource configuration error" ruleset="TIBCO conventions" prority="3"
			description="FTL Realm resource configuration error.">
			<configuration type="ftlsr:FTLRealmServerConnection">
				<property name="realmServerURL" check="configurable"/>
				<property name="secondaryRealmServerURL" check="configurable"/>
				<property name="applicationName" check="configurable"/>
				<property name="applicationInstanceIdentifier" check="configurable"/>
				<property name="username" check="configurable"/>
				<property name="password" check="configurable"/>
			</configuration>
		</rule>
	</resource>

	<xpathfunctions>
		<xpathfunction id="process">/bpws:process</xpathfunction>
		<xpathfunction id="scope">/bpws:process/bpws:scope</xpathfunction>
		<xpathfunction id="flow">/bpws:process/bpws:scope/bpws:flow</xpathfunction>
		<xpathfunction id="extensionActivity">//bpws:extensionActivity</xpathfunction>
		<xpathfunction id="extActivity">//tibex:extActivity</xpathfunction>
		<xpathfunction id="activityExtension">//tibex:activityExtension</xpathfunction>
		<xpathfunction id="activityExtensionConfig">//tibex:config</xpathfunction>
		<xpathfunction id="processInfo">/bpws:process/tibex:ProcessInfo</xpathfunction>
		<xpathfunction id="receiveEvent">//bpws:extensionActivity/tibex:receiveEvent</xpathfunction>
		<xpathfunction id="eventSource">//bpws:extensionActivity/tibex:receiveEvent/tibex:eventSource</xpathfunction>
		<xpathfunction id="documentation">/bpws:process/bpws:documentation</xpathfunction>
		<xpathfunction id="reply">//bpws:reply</xpathfunction>
		<xpathfunction id="layoutConstraint">//layoutConstraint</xpathfunction>
		<xpathfunction id="diagram">//notation:Diagram</xpathfunction>
	</xpathfunctions>
</tibrules>
